FROM python:3.12.2-slim-bookworm

LABEL maintainer="Bertrand Neron"
LABEL maintainer.email="bneron@pasteur.fr"
LABEL authors="Bertrand Neron; Eloi Littner; Matthieu Haudiquet; Amandine Perrin,Jean Cury and Eduardo PC Rocha"
LABEL package.version="2.0.4"
LABEL package.license="GPLv3"
LABEL package.homepage="https://github.com/gem-pasteur/Integron_Finder/"
LABEL publications="https://doi.org/10.3390/microorganisms10040700"


ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y &&\
    apt-get install -y --no-install-recommends hmmer infernal prodigal &&\
    apt-get clean -y

RUN pip3 install integron_finder==2.0.4

ENV DEBIAN_FRONTEND=teletype
ENV PYTHONIOENCODING=UTF-8
ENV MPLCONFIGDIR=/home/IF

RUN useradd -m IF
USER IF
WORKDIR /home/IF


ENTRYPOINT ["/usr/local/bin/integron_finder"]

CMD ['-h']
