FROM ubuntu:hirsute

LABEL maintainer="Bertrand Neron"
LABEL maintainer.email="bneron@pasteur.fr"
LABEL authors="Jean Cury; Thomas Jove; Marie Touchon; Bertrand Neron; Eduardo PC Rocha"
LABEL package.version="2.0dev"
LABEL package.license="GPLv3"
LABEL package.homepage="https://github.com/gem-pasteur/Integron_Finder/"
LABEL publications="https://doi.org/10.1093/nar/gkw319"


ARG DEBIAN_FRONTEND=noninteractive
ARG IF_GIT_URL="https://github.com/gem-pasteur/Integron_Finder.git"
ARG IF_GIT_TAG="dev"

RUN apt-get update -y &&\
    apt-get install -y --no-install-recommends python3 python3-pip python3-setuptools git hmmer infernal prodigal &&\
    apt-get install -y python3-numpy python3-pandas python3-matplotlib python3-biopython&&\
    apt-get clean -y

RUN cd /usr/local/src &&\
    git clone --depth 1 --branch ${IF_GIT_TAG} ${IF_GIT_URL} integron_finder &&\
    cd integron_finder &&\
    git checkout ${IF_GIT_TAG} &&\
    pip3 install . 

ENV DEBIAN_FRONTEND=teletype
ENV PYTHONIOENCODING=UTF-8
ENV MPLCONFIGDIR=/home/IF

RUN useradd -m IF
USER IF
WORKDIR /home/IF

ENTRYPOINT ["/usr/local/bin/integron_finder"]

CMD ['-h']
